Update links
Overv/VulkanTutorial pull request #263
Opened 2022-01-22 17:09 UTC by SaschaWillems

This PR updates a few of the links to point at current resources:

- Remove no longer maintained link to the Vulkan reference
- Update Vulkan spec link to the chunked 1.2 version
- Add link to the Khronos Vulkan Guide
- Update links in the tutorial chapters to the current Vulken 1.2 chunked spec

2022-01-25 19:51 UTC, Overv requested changes

2022-01-25 19:51 UTC, Overv commented on en/05_Uniform_buffers/01_Descriptor_pool_and_sets.md
> +You can find the full list of alignment requirements in [the specification](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap7.html#synchronization-pipeline-stages).
```suggestion
You can find the full list of alignment requirements in [the specification](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap15.html#interfaces-resources-layout).
```

2022-01-25 19:51 UTC, Overv commented on fr/10_Multisampling.md
> +[sample shading](hhttps://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap27.html#primsrast-sampleshading), qui
```suggestion
[sample shading](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap27.html#primsrast-sampleshading), qui
```

2022-01-25 19:51 UTC, Overv commented on en/06_Texture_mapping/00_Images.md
> +values are listed in [this table](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap7.html#synchronization-access-types)
```suggestion
values are listed in [this table](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap7.html#synchronization-access-types-supported)
```

2022-01-25 19:51 UTC, Overv commented on en/06_Texture_mapping/00_Images.md
> +happen. See [the documentation](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap7.html#synchronization-pipeline-stages)
```suggestion
happen. See [the documentation](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap7.html#VkPipelineStageFlagBits)
```

2022-01-25 19:51 UTC, Overv commented on fr/06_Texture_mapping/00_Images.md
> +[dans ce tableau](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap7.html#synchronization-access-types).
```suggestion
[dans ce tableau](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap7.html#synchronization-access-types-supported).
```

2022-01-25 19:51 UTC, Overv commented on fr/06_Texture_mapping/00_Images.md
> +[la documentation](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap7.html#synchronization-pipeline-stages)
```suggestion
[la documentation](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap7.html#VkPipelineStageFlagBits)
```

2022-02-06 13:24 UTC, SaschaWillems commented
Thanks for the suggested changes. I have updated the links accordingly and also updated them to point at the Vulkan 1.3 spec.

2022-02-06 13:44 UTC, merged